# This is a config for E2B sandbox template.
# You can use template ID (s3qoswoit0cio8stbay0) or template name (vibe-nextjs-bek-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-bek-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-bek-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-bek-2')

team_id = "0dcfb6aa-a7d5-48b4-9541-12bd01a4d73b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-bek-2"
template_id = "s3qoswoit0cio8stbay0"
